version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file: .env
  app:
    build: .
    command: "npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ".:/app"
    env_file: .env
